### ISSUE TITLE
All items are initially selected and can't unselect items.

### ISSUE THREAD

**Issue by AKILLIMUSTAFA** [hantrungkien/Bubble-Picker#2]
Firstly thank you all for your contribution.

# First Bug

I downloaded and ran the project. But all items are initially selected and can't unselect items.

![ashampoo_snap_26 temmuz 2018 persembe_12h22m47s_001_](https://user-images.githubusercontent.com/11073644/43257551-c4bcd2b2-90d8-11e8-9753-72a139489820.png)

# Second Bug

I create a new Android Studio Java Project. This is my mainactivity code: 

```
import android.content.res.TypedArray;
import android.graphics.Color;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;

import com.kienht.bubblepicker.model.PickerItem;
import com.kienht.bubblepicker.rendering.BubblePicker;

import java.util.ArrayList;

public class MainActivity extends AppCompatActivity{

    private BubblePicker picker;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        final String[] titles = getResources().getStringArray(R.array.countries);
        final TypedArray colors = getResources().obtainTypedArray(R.array.colors);
        final TypedArray images = getResources().obtainTypedArray(R.array.images);

        picker = (BubblePicker)findViewById(R.id.picker);
        ArrayList<PickerItem> listItems = new ArrayList<>();

        for (int i=0; i<6;++i){
            PickerItem item = new PickerItem(titles[i]);
            item.setColor(colors.getColor(i,Color.WHITE));
            item.setImgDrawable(images.getDrawable(i));
            item.setSelected(false);
            listItems.add(item);
        }
        picker.setDatas(listItems);
    }
}
```

But items appear too late on the screen and it needs to touch the screen. Again all items are initially selected and can't unselect items. gif showing how it works:

![2018-07-26_13-34-04](https://user-images.githubusercontent.com/11073644/43257948-d7a1f94c-90d9-11e8-94ce-aa85939050d3.gif)

**Comment by hantrungkien** [comment]
Dường như bạn đã không đọc document của tôi
please try: mBubblePicker.setAlwaysSelected(true);

**Comment by AKILLIMUSTAFA** [comment]
Thanks for the answer.
mBubblePicker.setAlwaysSelected(false); and mBubblePicker.setCenterImmediately(true); works for me.

**Comment by Ulugbe7** [comment]
how to change buble radius
